create database vendasjpa;
use vendasjpa;

CREATE TABLE CLIENTES(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    EMPRESA VARCHAR(45)
);

CREATE TABLE ENDERECO(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT(11),
    RUA VARCHAR(45),
    CIDADE VARCHAR(45),
    CEP VARCHAR(10),
    CONSTRAINT `FK_ENDERECO_CLIENTE` FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTES(ID)
);

CREATE TABLE PEDIDOS(
	NUMPEDIDO INT(11),
    IDPEDIDO INT(11), 
    DATAPEDIDO DATETIME,
    IDCLIENTE INT(11), 
    CATEGORIA VARCHAR(45), 
    CONSTRAINT `FK_PEDIDOS_CLIENTES` FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTES(ID), 
    CONSTRAINT `PK_COMPOSTA` PRIMARY KEY CLUSTERED (NUMPEDIDO, CATEGORIA)
);

DROP TABLE IF EXISTS ITENS;
CREATE TABLE ITENS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT, 
    NUMPEDIDO INT(11), 
    QUANTIDADE DOUBLE, 
    CATEGORIA VARCHAR(45), 
    CONSTRAINT `FK_ITENS_PEDIDOS_NUMPEDIDO` FOREIGN KEY(NUMPEDIDO) REFERENCES PEDIDOS(NUMPEDIDO)
    -- CONSTRAINT `FK_ITENS_PEDIDOS_CATEGORIA` FOREIGN KEY(CATEGORIA) REFERENCES PEDIDOS(CATEGORIA)
);

